<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223083910 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alerts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type JSON DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE subject_skills DROP CONSTRAINT fk_5d28df5723edc87');
        $this->addSql('ALTER TABLE subject_skills DROP CONSTRAINT fk_5d28df577ff61858');
        $this->addSql('ALTER TABLE subject_skills ADD CONSTRAINT FK_5D28DF5723EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject_skills ADD CONSTRAINT FK_5D28DF577FF61858 FOREIGN KEY (skills_id) REFERENCES skills (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE alerts');
        $this->addSql('ALTER TABLE subject_skills DROP CONSTRAINT FK_5D28DF5723EDC87');
        $this->addSql('ALTER TABLE subject_skills DROP CONSTRAINT FK_5D28DF577FF61858');
        $this->addSql('ALTER TABLE subject_skills ADD CONSTRAINT fk_5d28df5723edc87 FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subject_skills ADD CONSTRAINT fk_5d28df577ff61858 FOREIGN KEY (skills_id) REFERENCES skills (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
