<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260112101242 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE subject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, coefficient DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE subject_skill (subject_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (subject_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_4FAE25AF23EDC87 ON subject_skill (subject_id)');
        $this->addSql('CREATE INDEX IDX_4FAE25AF5585C142 ON subject_skill (skill_id)');
        $this->addSql('ALTER TABLE subject_skill ADD CONSTRAINT FK_4FAE25AF23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subject_skill ADD CONSTRAINT FK_4FAE25AF5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE subject_skill DROP CONSTRAINT FK_4FAE25AF23EDC87');
        $this->addSql('ALTER TABLE subject_skill DROP CONSTRAINT FK_4FAE25AF5585C142');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE subject_skill');
    }
}
