<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123123557 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE sections CASCADE');
        // 1. On garde la création de la NOUVELLE table 'sections'
        $this->addSql('CREATE TABLE sections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, training INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B964398909E143A ON sections (training_id)');
        $this->addSql('CREATE TABLE user_sections (user_id INT NOT NULL, sections_id INT NOT NULL, PRIMARY KEY (user_id, sections_id))');
        $this->addSql('CREATE INDEX IDX_CB1BA798A76ED395 ON user_sections (user_id)');
        $this->addSql('CREATE INDEX IDX_CB1BA798577906E4 ON user_sections (sections_id)');
        $this->addSql('ALTER TABLE sections ADD CONSTRAINT FK_2B964398909E143A FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_sections ADD CONSTRAINT FK_CB1BA798A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_sections ADD CONSTRAINT FK_CB1BA798577906E4 FOREIGN KEY (sections_id) REFERENCES sections (id) ON DELETE CASCADE');
        
        // 2. On garde l'ajout de la description dans training
        $this->addSql('ALTER TABLE training ADD description TEXT DEFAULT NULL');

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE classe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, duration INT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, training_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_8f87bf96befd98d1 ON classe (training_id)');
        $this->addSql('CREATE TABLE user_classe (user_id INT NOT NULL, classe_id INT NOT NULL, PRIMARY KEY (user_id, classe_id))');
        $this->addSql('CREATE INDEX idx_ead5a4aba76ed395 ON user_classe (user_id)');
        $this->addSql('CREATE INDEX idx_ead5a4ab8f5ea509 ON user_classe (classe_id)');
        $this->addSql('ALTER TABLE classe ADD CONSTRAINT fk_8f87bf96befd98d1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_classe ADD CONSTRAINT fk_ead5a4aba76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_classe ADD CONSTRAINT fk_ead5a4ab8f5ea509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sections DROP CONSTRAINT FK_2B964398909E143A');
        $this->addSql('ALTER TABLE user_sections DROP CONSTRAINT FK_CB1BA798A76ED395');
        $this->addSql('ALTER TABLE user_sections DROP CONSTRAINT FK_CB1BA798577906E4');
        $this->addSql('DROP TABLE sections');
        $this->addSql('DROP TABLE user_sections');
        $this->addSql('ALTER TABLE training DROP description');
    }
}
