<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123091007 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE classe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, duration INT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, training_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F87BF96BEFD98D1 ON classe (training_id)');
        $this->addSql('CREATE TABLE grade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grade DOUBLE PRECISION NOT NULL, subject_id INT NOT NULL, student_id INT NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_595AAE3423EDC87 ON grade (subject_id)');
        $this->addSql('CREATE INDEX IDX_595AAE34CB944F1A ON grade (student_id)');
        $this->addSql('CREATE INDEX IDX_595AAE3441807E1D ON grade (teacher_id)');
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, skill_unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E3DE477E248EE24 ON skill (skill_unit_id)');
        $this->addSql('CREATE TABLE skill_unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE subject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, coefficient DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE subject_skill (subject_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (subject_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_4FAE25AF23EDC87 ON subject_skill (subject_id)');
        $this->addSql('CREATE INDEX IDX_4FAE25AF5585C142 ON subject_skill (skill_id)');
        $this->addSql('CREATE TABLE training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, class_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE classe ADD CONSTRAINT FK_8F87BF96BEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE3423EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE3441807E1D FOREIGN KEY (teacher_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE477E248EE24 FOREIGN KEY (skill_unit_id) REFERENCES skill_unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject_skill ADD CONSTRAINT FK_4FAE25AF23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subject_skill ADD CONSTRAINT FK_4FAE25AF5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE classe DROP CONSTRAINT FK_8F87BF96BEFD98D1');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT FK_595AAE3423EDC87');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT FK_595AAE34CB944F1A');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT FK_595AAE3441807E1D');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT FK_5E3DE477E248EE24');
        $this->addSql('ALTER TABLE subject_skill DROP CONSTRAINT FK_4FAE25AF23EDC87');
        $this->addSql('ALTER TABLE subject_skill DROP CONSTRAINT FK_4FAE25AF5585C142');
        $this->addSql('DROP TABLE classe');
        $this->addSql('DROP TABLE grade');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE skill_unit');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE subject_skill');
        $this->addSql('DROP TABLE training');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
