<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123130204 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE classes DROP CONSTRAINT fk_2ed7ec5befd98d1');
        $this->addSql('ALTER TABLE user_classes DROP CONSTRAINT fk_5ae060cf9e225b24');
        $this->addSql('ALTER TABLE user_classes DROP CONSTRAINT fk_5ae060cfa76ed395');
        $this->addSql('DROP TABLE classes');
        $this->addSql('DROP TABLE user_classes');
        $this->addSql('ALTER TABLE sections DROP CONSTRAINT fk_2b964398909e143a');
        $this->addSql('DROP INDEX idx_2b964398909e143a');
        $this->addSql('ALTER TABLE sections RENAME COLUMN training_id_id TO training_id');
        $this->addSql('ALTER TABLE sections ADD CONSTRAINT FK_2B964398BEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_2B964398BEFD98D1 ON sections (training_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE classes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, duration INT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, training_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_2ed7ec5befd98d1 ON classes (training_id)');
        $this->addSql('CREATE TABLE user_classes (user_id INT NOT NULL, classes_id INT NOT NULL, PRIMARY KEY (user_id, classes_id))');
        $this->addSql('CREATE INDEX idx_5ae060cf9e225b24 ON user_classes (classes_id)');
        $this->addSql('CREATE INDEX idx_5ae060cfa76ed395 ON user_classes (user_id)');
        $this->addSql('ALTER TABLE classes ADD CONSTRAINT fk_2ed7ec5befd98d1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_classes ADD CONSTRAINT fk_5ae060cf9e225b24 FOREIGN KEY (classes_id) REFERENCES classes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_classes ADD CONSTRAINT fk_5ae060cfa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sections DROP CONSTRAINT FK_2B964398BEFD98D1');
        $this->addSql('DROP INDEX IDX_2B964398BEFD98D1');
        $this->addSql('ALTER TABLE sections RENAME COLUMN training_id TO training_id_id');
        $this->addSql('ALTER TABLE sections ADD CONSTRAINT fk_2b964398909e143a FOREIGN KEY (training_id_id) REFERENCES training (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_2b964398909e143a ON sections (training_id_id)');
    }
}
