<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123152007 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE grades (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grade DOUBLE PRECISION NOT NULL, subject_id INT NOT NULL, student_id INT NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AE3611023EDC87 ON grades (subject_id)');
        $this->addSql('CREATE INDEX IDX_3AE36110CB944F1A ON grades (student_id)');
        $this->addSql('CREATE INDEX IDX_3AE3611041807E1D ON grades (teacher_id)');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE3611023EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE3611041807E1D FOREIGN KEY (teacher_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT fk_595aae3423edc87');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT fk_595aae34cb944f1a');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT fk_595aae3441807e1d');
        $this->addSql('DROP TABLE grade');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE grade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grade DOUBLE PRECISION NOT NULL, subject_id INT NOT NULL, student_id INT NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_595aae34cb944f1a ON grade (student_id)');
        $this->addSql('CREATE INDEX idx_595aae3441807e1d ON grade (teacher_id)');
        $this->addSql('CREATE INDEX idx_595aae3423edc87 ON grade (subject_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT fk_595aae3423edc87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT fk_595aae34cb944f1a FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT fk_595aae3441807e1d FOREIGN KEY (teacher_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE3611023EDC87');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110CB944F1A');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE3611041807E1D');
        $this->addSql('DROP TABLE grades');
    }
}
