<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223074140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE skills (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, skill_unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5311670E248EE24 ON skills (skill_unit_id)');
        $this->addSql('CREATE TABLE subject_skills (subject_id INT NOT NULL, skills_id INT NOT NULL, PRIMARY KEY (subject_id, skills_id))');
        $this->addSql('CREATE INDEX IDX_5D28DF5723EDC87 ON subject_skills (subject_id)');
        $this->addSql('CREATE INDEX IDX_5D28DF577FF61858 ON subject_skills (skills_id)');
        $this->addSql('ALTER TABLE skills ADD CONSTRAINT FK_D5311670E248EE24 FOREIGN KEY (skill_unit_id) REFERENCES skill_unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject_skills ADD CONSTRAINT FK_5D28DF5723EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subject_skills ADD CONSTRAINT FK_5D28DF577FF61858 FOREIGN KEY (skills_id) REFERENCES skills (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT fk_5e3de477e248ee24');
        $this->addSql('ALTER TABLE subject_skill DROP CONSTRAINT fk_4fae25af5585c142');
        $this->addSql('ALTER TABLE subject_skill DROP CONSTRAINT fk_4fae25af23edc87');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE subject_skill');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, skill_unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_5e3de477e248ee24 ON skill (skill_unit_id)');
        $this->addSql('CREATE TABLE subject_skill (subject_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (subject_id, skill_id))');
        $this->addSql('CREATE INDEX idx_4fae25af5585c142 ON subject_skill (skill_id)');
        $this->addSql('CREATE INDEX idx_4fae25af23edc87 ON subject_skill (subject_id)');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT fk_5e3de477e248ee24 FOREIGN KEY (skill_unit_id) REFERENCES skill_unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subject_skill ADD CONSTRAINT fk_4fae25af5585c142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subject_skill ADD CONSTRAINT fk_4fae25af23edc87 FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skills DROP CONSTRAINT FK_D5311670E248EE24');
        $this->addSql('ALTER TABLE subject_skills DROP CONSTRAINT FK_5D28DF5723EDC87');
        $this->addSql('ALTER TABLE subject_skills DROP CONSTRAINT FK_5D28DF577FF61858');
        $this->addSql('DROP TABLE skills');
        $this->addSql('DROP TABLE subject_skills');
    }
}
