<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123122218 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE classes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, duration INT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, training_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2ED7EC5BEFD98D1 ON classes (training_id)');
        $this->addSql('CREATE TABLE user_classes (user_id INT NOT NULL, classes_id INT NOT NULL, PRIMARY KEY (user_id, classes_id))');
        $this->addSql('CREATE INDEX IDX_5AE060CFA76ED395 ON user_classes (user_id)');
        $this->addSql('CREATE INDEX IDX_5AE060CF9E225B24 ON user_classes (classes_id)');
        $this->addSql('ALTER TABLE classes ADD CONSTRAINT FK_2ED7EC5BEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_classes ADD CONSTRAINT FK_5AE060CFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_classes ADD CONSTRAINT FK_5AE060CF9E225B24 FOREIGN KEY (classes_id) REFERENCES classes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE classe DROP CONSTRAINT fk_8f87bf96befd98d1');
        $this->addSql('ALTER TABLE user_classe DROP CONSTRAINT fk_ead5a4aba76ed395');
        $this->addSql('ALTER TABLE user_classe DROP CONSTRAINT fk_ead5a4ab8f5ea509');
        $this->addSql('DROP TABLE classe');
        $this->addSql('DROP TABLE user_classe');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE classe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, duration INT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, training_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_8f87bf96befd98d1 ON classe (training_id)');
        $this->addSql('CREATE TABLE user_classe (user_id INT NOT NULL, classe_id INT NOT NULL, PRIMARY KEY (user_id, classe_id))');
        $this->addSql('CREATE INDEX idx_ead5a4aba76ed395 ON user_classe (user_id)');
        $this->addSql('CREATE INDEX idx_ead5a4ab8f5ea509 ON user_classe (classe_id)');
        $this->addSql('ALTER TABLE classe ADD CONSTRAINT fk_8f87bf96befd98d1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_classe ADD CONSTRAINT fk_ead5a4aba76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_classe ADD CONSTRAINT fk_ead5a4ab8f5ea509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE classes DROP CONSTRAINT FK_2ED7EC5BEFD98D1');
        $this->addSql('ALTER TABLE user_classes DROP CONSTRAINT FK_5AE060CFA76ED395');
        $this->addSql('ALTER TABLE user_classes DROP CONSTRAINT FK_5AE060CF9E225B24');
        $this->addSql('DROP TABLE classes');
        $this->addSql('DROP TABLE user_classes');
    }
}
